import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import prisma from '../lib/prisma'
import { useEffect } from 'react'
import LoginButton from '../components/login-btn'
/*
export const username = async () => {
  const firstUser = await prisma.user.findFirst()
  const name = firstUser?.name
  if (name) {
    return {
      props: { name }
    }
  } else {
    return { props: { name: null } }
  }
} */

const Home = (props: { [key: string]: any }) => {
  return (
    <div>
      <Head>
        <title>PharmaBox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>App Main Page</h1>
        <LoginButton />
      </div>
    </div>
  )
}

export default Home
