import Head from 'next/head'

import { useClerk } from '@clerk/clerk-react'
import { withServerSideAuth } from '@clerk/nextjs/ssr'
import getUserDetails from '../helpers/user-details'
import Page from '../components/Page'
import { ServerPageProps } from '../types/types'
import { Text } from 'grommet'
const Home = ({ user }: ServerPageProps) => {
  const { signOut } = useClerk()
  return (
    <>
      <Head>
        <title>PharmaBox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page user={user}>
        <Text>{user.first_name}</Text>
        <button onClick={() => signOut()}>Sign out</button>
      </Page>
    </>
  )
}

export default Home

export const getServerSideProps = withServerSideAuth(
  async ({ req }) => {
    const { userId } = req.auth
    if (userId) {
      return getUserDetails(userId)
    }
    return { props: { userId } }
  },
  { loadUser: true }
)
