import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import prisma from '../lib/prisma'
import Link from 'next/link'
import { useUser } from '@clerk/nextjs'
import { useClerk } from '@clerk/clerk-react'
import { withServerSideAuth } from '@clerk/nextjs/ssr'

const Home = (props: { [key: string]: any }) => {
  const { isLoaded, isSignedIn, user } = useUser()
  const { signOut } = useClerk()
  if (!isSignedIn) {
    return (
      <div>
        <div>Not signed In</div>
        <Link href="/sign-up">Sign Up</Link>
      </div>
    )
  }

  return (
    <div>
      <Head>
        <title>Create Next App made</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>{user.firstName}</div>
        <button onClick={() => signOut()}>Sign out</button>
      </main>
    </div>
  )
}

export default Home

export const getServerSideProps = withServerSideAuth(
  async ({ req }) => {
    const { userId } = req.auth
    if (userId) {
      return prisma.user
        .findUnique({
          where: {
            id: userId
          }
        })
        .then((user) => {
          return { props: { userId } }
        })
    }

    return { props: { userId } }
  },
  { loadUser: true }
)
