#!/bin/bash

set -o allexport
source .env.development
set +o allexport

echo $DATABASE_URL
npx prisma migrate dev

# set -o allexport
# source .env.production
# set +o allexport

# echo $DATABASE_URL
# npx prisma migrate dev